name: macOS Catalina 10.15
on:
  # TODO: Fix build on macOS, remove the next line and uncomment the following lines.
  - workflow_dispatch  # allow manual trigger
  #push:
  #  branches:
  #    - master
  #pull_request:
  #  branches:
  #    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: macOS Catalina 10.15
      run: |
        brew install automake libevent openssl@1.1 bison
        export PATH="/usr/local/opt/bison/bin:$PATH"
        export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/bison/lib"
        export CFLAGS=-I/usr/local/opt/openssl@1.1/include
        ./bootstrap
        ./configure --with-gnu-ld --sysconfdir=/etc/mail --with-auth-pam
        make
        sudo make install
